Исправлено начальное состояние
IgorSamohin/mental-care-by-marusia pull request #15
Opened 2022-03-29 21:36 UTC by IlyaAAAA

Из-за того, что prev_id был int, он по дефолту инициализировался нулем, и начально состояние было 0, а не -1

2022-03-30 06:49 UTC, IgorSamohin requested changes

2022-03-30 06:49 UTC, IgorSamohin commented on src/main/java/com/polis/api/MarusiaService.java
> +        logger.info("curr id : " + request.state.session.prevStateId);
Мне кажется, что если ты хочешь это логировать, то тут нужен уровень debug. А вообще, какой смысл в данном логировании?

2022-03-30 06:49 UTC, IgorSamohin commented on src/main/java/com/polis/api/MarusiaService.java
> +        State nextState = repository.getNextState(request.state.session.prevStateId, request.request.command);
Ты уверен, что request.state.session никогда не равен null? Мне всегда казалось, что если парсер не находит подходящего объекта в json'e, то он ставит null, а не генерирует пустой объект

2022-03-30 14:15 UTC, IlyaAAAA commented on src/main/java/com/polis/api/MarusiaService.java
> +        logger.info("curr id : " + request.state.session.prevStateId);
убрал

2022-03-30 14:17 UTC, IlyaAAAA commented on src/main/java/com/polis/api/MarusiaService.java
> +        State nextState = repository.getNextState(request.state.session.prevStateId, request.request.command);
Вроде бы не равен
![image](https://user-images.githubusercontent.com/46154942/160856136-b56c0b84-04f9-4ee6-ac4e-f5ed0da9caaa.png)
session конструируется, а вот в ней он не находит prevStateId, и он мб null

2022-03-30 14:20 UTC, IlyaAAAA commented
Навигацию назад нужна? А еще в каждом ли состояние должна быть возможность завершить скилл или в начало перейти?

2022-03-30 14:46 UTC, IgorSamohin commented
Навигация назад - навигация в начало? Если да, то нужна, если нет, то у нас нет необходимости делать переход на 1 состояние назад, поскольку в большинстве случаев одно состояние назад == начало.

Завершить скилл нужно уметь из любого состояния. Кстати, кажется, что стоит фразы завершения скилла вынести из Tranistion'ов в метод парсинга фразы, чтобы не плодить одинаковые строки (но это не точно)

2022-03-30 14:48 UTC, IgorSamohin approved these changes

2022-03-30 14:55 UTC, IlyaAAAA commented
пока не вмерживай

2022-04-03 21:39 UTC, IgorSamohin commented
Это можно мержить?

2022-04-03 21:59 UTC, IlyaAAAA commented
> Это можно мержить? 

Да

2022-04-03 22:15 UTC, merged