Изменена навигация
IgorSamohin/mental-care-by-marusia pull request #20
Opened 2022-04-07 12:24 UTC by IlyaAAAA

2022-04-07 12:30 UTC, IlyaAAAA commented
пока добавил управляющих фраз, убрал пунктуацию, и добавил команды ответов, которые как подсказки появляются

с переходами пока застрял

2022-04-08 19:20 UTC, IgorSamohin commented
В мастере произошли крупные изменения из-за мержа пул реквестов. Аккуратненько замержи мастера в свою ветку

2022-04-19 16:15 UTC, IgorSamohin requested changes

2022-04-19 16:15 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/State.java
> +    //FIXME возможно так плохо, тк можно вызвать getAnswer().text и сразу после этого getAnswer().tts и буду разные
Никаких проблем не будет, если назвать метод getRandomAnswer()

2022-04-19 16:15 UTC, IgorSamohin commented on src/main/java/com/polis/api/RandomUtils.java
> +    private static final Random random = new Random();
Я думаю, что не нужно использовать такой синглтон. Посмотри внимательнее на реализаицю Random.nextInt(). Там внутри лежит cas-loop. Если будет большая конкурентность на обращении к твоему синглтону, то выполнение будет очень медленным. Лучше взять какой-нибудь ThreadLocalRandom или просто по рандому в каждый стейт

2022-04-19 16:15 UTC, IgorSamohin commented on src/main/java/com/polis/api/MarusiaService.java
> +        logger.info("prev state from request: " + request.getState().session.prevStateId);
Опять логи c уровнем info просочились в pr

2022-04-19 16:15 UTC, IgorSamohin commented on src/main/java/com/polis/api/MarusiaService.java
> +        String tts = marusiaAnswer.tts;
Вот это бессмысленно. Можно заинлайнить в 58, 59 строки

2022-04-19 16:15 UTC, IgorSamohin commented on src/main/java/com/polis/api/MarusiaService.java
> +        List<Button> buttonList = state.getButtons().stream().map(Button::new).collect(Collectors.toList());
Ты здесь будешь для каждого запроса поднимать стрим и генерить объекты? У нас фиксированное количество состояний и кнопок к ним. Кажется, что будет быстрее хранить в стейтах сразу готовые объекты кнопок

2022-04-19 16:15 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/Data.java
> +        states.put(-3, new State(-3, new SingleAnswer(MarusiaAnswer.EXIT_ANSWER), allTransitions, ZoneButtons.DEFAULT.buttons, false));
Здесь не нужны allTransitions. -3 как Омск. Отсюда выхода нет) С кнопками аналогично

2022-04-19 16:15 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/RepositoryImpl.java
>          if (nextStateId == -1) {
В твоей реализации нельзя попасть в -1 (это START_ANSWER)

2022-04-19 16:15 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/State.java
> +    private List<String> buttons;
`List<Button>`

2022-04-20 21:04 UTC, IlyaAAAA commented on src/main/java/com/polis/api/MarusiaService.java
> +        logger.info("prev state from request: " + request.getState().session.prevStateId);
+

2022-04-20 21:04 UTC, IlyaAAAA commented on src/main/java/com/polis/api/MarusiaService.java
> +        String tts = marusiaAnswer.tts;
+

2022-04-20 21:05 UTC, IlyaAAAA commented on src/main/java/com/polis/api/storage/RepositoryImpl.java
>          if (nextStateId == -1) {
+

2022-04-20 21:05 UTC, IlyaAAAA commented on src/main/java/com/polis/api/storage/State.java
> +    private List<String> buttons;
+

2022-04-20 21:41 UTC, IgorSamohin commented
LGTM

2022-04-20 21:41 UTC, IgorSamohin approved these changes

2022-04-21 07:55 UTC, merged