Improve speech recognition. part 1
IgorSamohin/mental-care-by-marusia pull request #21
Opened 2022-04-10 01:01 UTC by sdimosik

2022-04-10 19:27 UTC, IgorSamohin requested changes
Меня не устраивают односложные фразы в качестве команды абсолютно везде. Я понимаю, что использование библиотеки может привести к ложным срабатыванием из-за общих слов ("давай", "что" и т.д.), но мне кажется, что не приведет, если докрутить сравнение. Так сказать, докажи, что я не прав на примере.

2022-04-10 19:27 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/MarusiaCommand.java
> +        "выйди",
Это команда выхода из скилла

2022-04-10 19:27 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/MarusiaCommand.java
> +        "заново",
Эта команда может подразумеваться как повторение какой-то ветки (т.е. аналог "еще") - лучше ее убрать. Аналогичные рассуждения с "по новой"

2022-04-10 19:27 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/MarusiaCommand.java
> +    HELP_SEDATION(
Мне казалось, что это переход типа "Как ты можешь меня успокоить", подразумевающий в качестве ответа справочную информацию, а не действия по успокоению. В данный момент этот переход полностью совпадает с SEDATION

2022-04-10 19:27 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/MarusiaCommand.java
> +    HELP_DISTRACTION(
Аналогично с HELP_SEDATION. Полное совпадение с DISTRACTION

2022-04-10 19:27 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/Transition.java
> +            int res = FuzzySearch.weightedRatio(userInput, synonym);
Здесь теперь можно не сразу выводить тру, если было совпадение > 80, а сделать накопительный эффект и прочекать все команды до конца, а потом понять, какой максимальный, или возможно будет смысл делать вывод не на основании одного совпадения, а на всех совпадениях (с помощью какой-нибудь типа агрегаторной функции). Кажется, что это позволит понизить порог срабатывания и увеличить точность.

2022-04-10 20:18 UTC, sdimosik commented on src/main/java/com/polis/api/storage/MarusiaCommand.java
> +    HELP_SEDATION(
Потому что так и должно быть) 
Мы запрашиваем что мы вообще можем и в зависимости от ответа переходим на нужную там ветку...
(как минимум транзишны сделаны так сейчас)

2022-04-10 20:20 UTC, sdimosik commented on src/main/java/com/polis/api/storage/Transition.java
> +            int res = FuzzySearch.weightedRatio(userInput, synonym);
Ну это конечно круто, только накопительный эффект может дать больше ложных совпадений. Например, если все штуки особо не подходят, но в итоге они все норм (вообще надо проверять)

2022-04-10 20:21 UTC, sdimosik commented
Так а как ты по-другому хочешь отслеживать что-то? 
Общие слова всегда нужно пропускать, они не несут смысла (это информационный шум)
Есть слова триггеры, по которым мы и определяем что делать дальше
Просто нужно сделать их уникальными

2022-04-10 20:24 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/MarusiaCommand.java
> +    HELP_SEDATION(
Нет, так не должно быть. Посмотри схему внимательнее. В зависимости от команды Маруся действует по-разному, а у тебя 2 разные команды будут работать из одного состояния с одними и теми же словами

2022-04-10 20:53 UTC, IgorSamohin commented
Во-первых, пользователь будет делать запрос вместе с этими общими словами. Как следствие, в данной реализации у тебя вообще почти не будет сработавших переходов. 
Во-вторых, общие слова не всегда бессмысленны. В случае коротких фраз эти слова как раз позволят поднять процент совпадения двух фраз. Например, есть переход "музыка", пользователь сказал "включи музыку". Слово "включи" ты откинешь, как общее и будешь сравнивать "музыка" и "музыку". Отличие - 17%. Если бы ты не отбросил это слово и переход был бы "включи музыку", то отличие было бы 8%. Смекаешь? Пример, конечно же, искусственный, но не лишенный смысла. 

Еще раз: твоя задача заключалась в том, чтобы сделать как можно больше осмысленных фраз к каждому переходу, которые бы не пересекались с другими переходами (т.е. чтобы у нас качественно работало построчное сравнение) и уже к этим фразам я предлагал применять более умное сравнение.

2022-04-29 07:00 UTC, Marashov-Alexander commented on src/main/java/com/polis/api/storage/MarusiaCommand.java
>  public enum MarusiaCommand {
Есть ли какие-то обоснования, почему для команд используется enum?
На мой взгляд, это не очень удобно:
наверняка ваши команды и ключевые слова к ним будут меняться (например, захочется добавить новую / убрать лишнее ключевое слово или наоборот добавить его).
И в случае, когда все ваши команды/слова сидят в enum'е, вам придется вносить изменения в код, что потребует пересборку артефакта.
Я бы построил архитектуру так, чтобы была возможность подключения внешней конфигурации, из которой ваше приложение тянуло бы команды.
Самый простой вариант - обычный текстовый файл конфигурации в удобном для вас формате)
Если понадобится - в дальнейшем вы сможете заменить его и на что-то более классное

2022-04-29 07:00 UTC, Marashov-Alexander commented on src/main/java/com/polis/api/storage/Transition.java
>      public boolean mustGo(String userInput) {
А в какой форме приходит параметр userInput?
Это уже распознанное Марусей слово / фраза?

2022-04-29 07:00 UTC, Marashov-Alexander commented on src/main/java/com/polis/api/storage/Data.java
>                          new Transition(-3, MarusiaCommand.EXIT),
(комментарий к строчке 9)
Я бы придерживался спринговой концепции и в этом классе)
Текущий вариант подразумевает, что ваши данные доступны откуда угодно, из любого класса, что не оч круто.
Если добавить @Component аннотацию, переименовать класс во что-то типа DataProvider, заменить static поля на обычные и цеплять экземпляр класса по концепции спринга как зависимость для других классов,
то код будет более единообразным и даже более безопасным (вы будете контролировать доступ к данным, а не отдавать их абсолютно всем)

2022-04-29 08:27 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/Transition.java
>      public boolean mustGo(String userInput) {
Да, это фраза, которую Маруся распознала и нормализовала. Она рядом еще отправляет массив токенов (отдельных слов), из которых исключены всякие предлоги, слова-паразиты и прочий мусор, но мы этот массив пока не используем

2022-04-29 08:31 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/MarusiaCommand.java
>  public enum MarusiaCommand {
Enum тут лежит с самого начала проекта, когда все было чуть-чуть по-другому. В остальном, с утверждением согласен

2022-05-02 20:10 UTC, IgorSamohin commented
Предлагаю заморозить этот реквест и переключиться на другие задачи, поскольку сейчас данная функциональность не является приоритетной

2022-05-02 20:10 UTC, closed without merging