Random content 27
IgorSamohin/mental-care-by-marusia pull request #35
Opened 2022-05-06 19:18 UTC by IlyaAAAA

Close #27

2022-05-06 19:22 UTC, IlyaAAAA commented
Пока сделал так, чет не могу придумать как с (видео) и (советами, дых упражнениями) обойтись
Насчет плееров, то состояниям, которые работают с ними, нужно иметь сразу готовый список плееров и из него выбирать

2022-05-06 20:34 UTC, IgorSamohin requested changes
Данная реализация - немного не то, что я хотел видеть изначально. У нас уже есть AudioPlayerProvider, где для каждого id состояния задается свой набор песен. 

Я предлагаю сделать обертку, в которую мы как прежде будем закидывать этот набор песен. Эту обертку передавать в State и state при запросе плеера будет говорить обертке: "дай плеер с n рандомных песен". Обертка будет формировать плеер и плеер будет возвращаться

С советами и видео нужно поступить примерно так же. В случае с видео при запросе текста у стейта можно просто проверять, есть ли видео обертка. И если есть, то рандомный видос пихать в строку с ответом (можно даже String.format использовать для этого)

2022-05-06 20:34 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/media/Media.java
> +                    5. На счет десять выдохните полностью через рот.
Мне кажется, цифры не очень хорошо звучат в исполнении Маруси. Проще, чтобы она просто сказала, что делать и все. А еще ты удалил 2 пункта, которые не просто так были в упражнении

2022-05-06 20:34 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/media/Media.java
> +            "Превращайте неудачи в будущие успехи"),
Какие-то странные советы, если честно. Одна половина звучит, как цитаты из пацанских пабликов, другая не совсем подходит под борьбу со стрессом. 
Мне кажется, что стоит оставить и немного раскрутить эти:

> "Занимайтесь спортом и чаще бывайте на природе."

> "Позвоните близким и расскажите о проблеме"

> "Не позволяй себе излишне предаваться чувствам вины и стыда. Это не поможет тебе добиться успеха."

2022-05-06 20:34 UTC, IgorSamohin commented on src/main/java/com/polis/api/MarusiaService.java
> +    private MediaProvider mediaProvider;
Этого точно здесь быть не должно. Все провайдеры не должны проникать дальше StateFactory. Они изначально нужны исключительно, чтобы данные удобно хранить и по стейтам удобно раскидывать

2022-05-06 20:34 UTC, IgorSamohin commented on src/main/java/com/polis/api/MarusiaService.java
> +        }
Хардкодный хардкод, нарушающий все, что можно нарушить. Это точно нужно убирать

2022-05-06 20:34 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/State.java
> +        return audioPlayers == null && false;
В такой интерпретации данный метод бессмысленный. Он, конечно, в любом случае не нужен и его вообще нужно убрать, но это другой разговор

2022-05-06 20:43 UTC, IlyaAAAA commented
> Данная реализация - немного не то, что я хотел видеть изначально. У нас уже есть AudioPlayerProvider, где для каждого id состояния задается свой набор песен.
> 
> Я предлагаю сделать обертку, в которую мы как прежде будем закидывать этот набор песен. Эту обертку передавать в State и state при запросе плеера будет говорить обертке: "дай плеер с n рандомных песен". Обертка будет формировать плеер и плеер будет возвращаться
> 
> С советами и видео нужно поступить примерно так же. В случае с видео при запросе текста у стейта можно просто проверять, есть ли видео обертка. И если есть, то рандомный видос пихать в строку с ответом (можно даже String.format использовать для этого)

Да, я чет запутался, надо было плейлисты рандомные, я чет другое сделал. Там проблема в том, что все равно надо будет в ответе генерить новый AudioPlayer, т.к сетать плейлисты в текущий - неправильно.

2022-05-08 10:58 UTC, IlyaAAAA commented on src/main/java/com/polis/api/storage/media/Media.java
> +                    5. На счет десять выдохните полностью через рот.
Про цифры забыл, а удалил, чтобы два упражнения хотя бы были

2022-05-08 11:32 UTC, IgorSamohin requested changes
Есть ощущение, что вот эта вот вся структура с получением аудио имеет излишнюю сложность. Пришлось подумать, чтобы понять, откуда все достается. Тут 2 варианта: первый - я тупой и все ок, второй - есть небольшой оверинжиниринг и нужно немного переделать. 

Если поправишь замечания, то, кажется, что на этом можно закончить мучать аудио, так что сейчас можно не переделывать. Если глазам станет совсем больно смотреть на это, то переделаем

2022-05-08 11:32 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/model/AdviceModel.java
> +        this.advices = Arrays.stream(advices).toList();
Не вижу в похожих местах поднимать стрим, чтобы просто вызвать toList. Проще вызвать Arrays.asList сразу. toList как раз это и делает внутри
![image](https://user-images.githubusercontent.com/16742075/167293554-432a6a23-016c-43c4-a05e-0b329f59703b.png)

2022-05-08 11:32 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/model/BreathExerciseModel.java
> +        this.exercises = Arrays.stream(exercises).toList();
Комментарий выше

2022-05-08 11:32 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/providers/StateFactory.java
> +        return new State(stateId, new Answer(answer.text(), answer.tts(), answer.isRepeatable()), transitions, buttons, commands, audio, breathExerciseModel, adviceModel);
Мб стоит внутри answer сделать метод, который бы возвращал Answer и мы бы его и передавали внутрь state?

2022-05-08 11:32 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/media/Media.java
> +public enum Media {
Поправь меня, если я ошибаюсь, но мне кажется, что это нигде не используется

2022-05-08 11:32 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/media/Media.java
> +            "От депрессии спасают коты и репрессии.",
btw советы все еще такие себе.... Лучше их не использовать

2022-05-08 11:32 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/providers/AudioProvider.java
> +@RequiredArgsConstructor
Технологии, конечно, но я в последнюю очередь посмотрел на аннотации, когда искал, где же инициализируются провайдеры

2022-05-08 11:32 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/model/AudioModel.java
> +        return new PlayList[]{playList.get(index)};
То есть в плейлисте всегда будет только один трек? Я думал, что мы будем несколько треков кидать. Штук 5, например

2022-05-08 12:22 UTC, IlyaAAAA commented on src/main/java/com/polis/api/storage/providers/StateFactory.java
> +        return new State(stateId, new Answer(answer.text(), answer.tts(), answer.isRepeatable()), transitions, buttons, commands, audio, breathExerciseModel, adviceModel);
Ты имеешь в виду статик метод? типо Answer.from(text,tts)?

2022-05-08 12:28 UTC, IlyaAAAA commented
Картинки, кстати, вообще нужны?

2022-05-08 12:28 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/providers/StateFactory.java
> +        return new State(stateId, new Answer(answer.text(), answer.tts(), answer.isRepeatable()), transitions, buttons, commands, audio, breathExerciseModel, adviceModel);
Нет, сейчас идет вызов answer.text() и answer.tts() и все это заворачивается в new Answer. Хочу вызвать какой-нибудь answer.getAnswer(), который внутри сконструирует new Answer. И да, название переменной нужно бы поменять, а то тавтология какая-то получается

2022-05-08 12:29 UTC, IgorSamohin commented
Пока нет, но то, что добавил, пусть будет

2022-05-08 12:31 UTC, IlyaAAAA commented
> Пока нет, но то, что добавил, пусть будет

я пока не добавил

2022-05-08 12:40 UTC, IlyaAAAA commented on src/main/java/com/polis/api/storage/providers/StateFactory.java
> +        return new State(stateId, new Answer(answer.text(), answer.tts(), answer.isRepeatable()), transitions, buttons, commands, audio, breathExerciseModel, adviceModel);
а, так это одно и тоже по факту, я тогда удалю, что я сделал

2022-05-08 15:30 UTC, IgorSamohin requested changes

2022-05-08 15:30 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/model/AudioModel.java
> +        Collections.shuffle(list);
Мне кажется, что взять PLAYLIST_SIZE песен из списке дешевле, чем переупорядочивать весь список

2022-05-08 15:30 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/model/AudioModel.java
> +    private PlayList[] getRandomPlayListWithOneAudio() {
Это теперь можно удалить

2022-05-08 16:16 UTC, IlyaAAAA commented on src/main/java/com/polis/api/storage/model/AudioModel.java
> +        Collections.shuffle(list);
ну можно рандомить from, который будет от 0 до list.size() - PLAYLIST_SIZE, и уже оттуда брать subList(from, PLAYLIST_SIZE), но тогда по факту они не так часто будут отличаться

2022-05-08 16:16 UTC, IlyaAAAA commented on src/main/java/com/polis/api/storage/model/AudioModel.java
> +        Collections.shuffle(list);
эти плейлисты

2022-05-08 16:24 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/model/AudioModel.java
> +        Collections.shuffle(list);
Чел, можно просто рандомить PLAYLIST_SIZE уникальных индексов, которые будут от 0 до playList.length и возвращать массив элементов, находящихся на этих индексах в исходном массиве. Этот вариант будет быстрее просто из-за того, что шаффл всего массива будет для каждого элемента вычислять рандомное число, которое может быть сильно больше PLAYLIST_SIZE

2022-05-09 09:24 UTC, IgorSamohin approved these changes

2022-05-09 09:25 UTC, merged