Добавлена игра на счет чисел
IgorSamohin/mental-care-by-marusia pull request #39
Opened 2022-05-11 14:16 UTC by IlyaAAAA

1) Пока сделал так, кажется, что эта игра не ложится под то, как у нас стейты сделаны,
2) Если выбрать конечное число большое, то, как я понял нельзя игру завершить, (говоришь фразу, которая содержит стоп, все, хватит, прилетает on_interrupt, дальше сессия обрывается)

P.S
Для первого можно как и до этого делали, в стейте завести переменную с игрой, при ответе чекать на налл, но надо будет передавать в ответ тогда что-то, т.к мы отдаем не заготовленный ответ, а ответ, который зависит от условий

2022-05-11 19:23 UTC, IlyaAAAA commented
пока прост добавил две игры, чтобы работало хотя бы

2022-05-15 15:01 UTC, IgorSamohin requested changes
1. Мне кажется, что стоит объединить два игровых сервиса в какой-нибудь один, который сам будет понимать, какая идет игра, сам будет парсить userInput и сам будет обращаться в репозиторий за текстом с ответом Маруси. 
2. Идея про ограничение числа в 100 - странная. Пусть число будет хотя бы в пределах Integer (только нужно будет обработать случай, когда юзер дает слишком большое или маленькое число)
3. Я не до конца понял, зачем нужно хранить и постоянно передавать туда-сюда endGameNumber = -1 и prevNumberGame = -1? Если это просто обозначение, что игры не было, то с таким же успехом можно просто сделать это поле Integer и повесить аннотацию JsonInclude(JsonInclude.Include.NON_NULL). Тогда все проверки можно заменить на проверку на нул и при конце игры обнулять все эти поля.

2022-05-15 15:01 UTC, IgorSamohin commented on src/main/java/com/polis/api/game/CountTaskService.java
> +                        "Давайте я начну! Один",
Хотелось бы, чтобы все ответы (в том числе и ответы для игры) хранились в одном месте (в MarusiaAnswerProvider). Легкого решения я пока что не вижу - придется id этих ответов хадкодить, что тоже не очень круто, но, наверное, лучше, чем сейчас.

2022-05-15 15:01 UTC, IgorSamohin commented on src/main/java/com/polis/api/game/GuessNumberAnswer.java
> +        int endGameNUmber
> endGameNUmber

У вас имени поля плохо стало

2022-05-15 15:01 UTC, IgorSamohin commented on src/main/java/com/polis/api/utils/NumberTransformUtils.java
> +            return -1;
Какой смысл здесь возвращать -1, если ты все равно знаешь, что у тебя там либо число в каком-то виде, либо ошибка? Если там не текстовый формат, то нужно попробовать попарсить через Integer.parseInt() и если и это не получится, то кинуть исключение, которое сверху поймается и будет выдан ответ о неправильном вводе

2022-05-15 15:01 UTC, IgorSamohin commented on src/main/java/com/polis/api/game/GuessNumberService.java
> +            int number = numberFromString == -1 ? Integer.parseInt(userInput) : numberFromString;
Собственно вот это нужно внутри Number...Utils делать

2022-05-15 15:01 UTC, IgorSamohin commented on src/main/java/com/polis/api/storage/providers/ButtonsProvider.java
> +        map.put(8, new ButtonsModel(ZoneButtons.GUESS_GAME));  //йога
Комментарий не тот

2022-05-15 15:01 UTC, IgorSamohin commented on src/main/java/com/polis/api/game/GameAnswer.java
> +    public GameAnswer(String text, String tts, boolean endGame, int prevNumber, int endGameNUmber) {
Конструктор бессмысленный

2022-05-15 15:05 UTC, IgorSamohin commented on src/main/java/com/polis/api/game/CountTaskService.java
> +                        "Давайте я начну! Один",
То же самое, кстати, касается комады "Да" в MarusiaService. Все команды нужно хранить в одном месте. Делать проверки на совпадения тоже нужно в одном месте.

2022-05-17 14:41 UTC, IgorSamohin commented
Можешь еще конфликы помержить, пожалуйста?

2022-05-17 20:00 UTC, IgorSamohin approved these changes
-karma тебе за то, что данные лежат не вместе с остальными

2022-05-17 20:01 UTC, merged